language:
  java

jdk:
  oraclejdk8

cache:
  directories:
    -$HOME/.m2

sudo:
  false

install:
  true

before_script:
  - ./db/runHSQLDBServer.sh &
  
script:
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
