language:
  java

jdk:
  oraclejdk8

cache:
  directories:
    -$HOME / .m2

sudo:
  false

before_script:
  - ./db/runHSQLDBServer.sh &
  
script:
  - mvn clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)